client_config_backend: file
client_config:
    client_id: 967752841352-d4hdevogt1psgok46rpnajcd4i9gaa08.apps.googleusercontent.com
    client_secret: AYHMpDTgWrSHm_4m89PpcCEm

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
